# todo: update
services:
  db:
    image: bitnami/postgresql:latest
    ports:
      - 54321:5432
    environment:
      POSTGRES_DB: todo_db
      POSTGRES_USER: todo
      POSTGRES_PASSWORD: todo

  backend:
    build: ./Back/TaskManager
    depends_on:
      - db
    restart: on-failure
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: todo_db
      DB_USER: todo
      DB_PASSWORD: todo
    ports:
      - "8888:8080"

  frontend:
    build: ./Front
    environment:
    # The other solution could be the reverse proxsy - front makes requests to localhost:3000/api/tasks and nginx will redirect the requests to http://backend:8080/api/taks. This requires separate nginx configuration.
      API_URL: http://localhost:8888
    depends_on:
      - backend
    ports:
      - "3000:80"